export const themes = [
  'Modern',
  'Neutral',
  'Monochromatic',
  'Complementary',
  'Cyberpunk',
  'Tiktok',
  'Twitter',
  'Instagram',
  'Analogous',
  'Warm',
  'Cool',
  'Pastel',
  'Black and white',
  'Earthy',
  'Vintage',
  'Minimalist',
  'Scandinavian',
  'Bohemian',
  'High-Contrast',
  'Bright',
  'Ocean-inspired',
  'Rustic',
  'Tropical',
  'Bold',
  'Jewel-toned',
  'Art Deco',
  'Mediterranean',
  'Traditional',
  'Beachy',
  'Moody',
  'Urban',
  'Contemporary',
  'Retro',
  'Whimsical',
  'Zen',
  'Industrial',
  'Biophilic',
  'Farmhouse',
  'Japanese Design',
  'Coastal',
  'Cottagecore',
  'French Country',
  'Maximalist',
  'Art Nouveau',
  'Baroque',
  'Vaporwave',
  'Ski Chalet',
  'Sketch',
  'Christmas',
  'Tribal',
  'Medieval',
  'Chinese New Year',
  'Halloween'
];
export const rooms = [
  'Living Room',
  'Dining Room',
  'Gaming Room',
  'Bedroom',
  'Bathroom',
  'Office',
  'Kitchen',
  'Guest Room',
  'Laundry Room',
  'Home Theater',
  'Playroom',
  'Music Room',
  'Exercise Room',
  'Library',
  'Sunroom',
  'Mudroom',
  'Attic',
  'Basement',
  'Pantry',
  'Wine Cellar',
  'Garage',
  'Outdoor Living Space',
  'Pool Room',
  'Study Room',
  'Home Office',
  'House Exterior',
  'Outdoor Pool Area',
  'Outdoor Patio',
  'Outdoor Garden',
  'Meeting Room',
  'Workshop',
  'Fitness Gym',
  'Coffee Shop',
  'Clothing Store',
  'Walk-in Closet',
  'Toilet',
  'Restaurant',
  'Coworking Space',
  'Hotel Lobby',
  'Hotel Room',
  'Hotel Bathroom',
  'Exhibition Space',
  'Onsen',
  'Drop Zone'
];
